version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - MIGRATION_VERSION=${MIGRATION_VERSION:-latest}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - .env:/config/env
      - ./migrations:/migrations/
      - ./init_scripts:/docker-entrypoint-initdb.d

  data_generation:
    build: ./data_generation
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PORT=5432
      - NUM_RECORDS=${ENTITIES_QUANTITY:-1000000}
    volumes:
      - ./data_generation:/src
    depends_on:
      - postgres

  performance_test:
    build: ./performance_test
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PORT=5432
      - ATTEMPTS=${ATTEMPTS:-3}
    volumes:
      - ./performance_test:/src
      - ./performance_test/results:/src/results