version: '3'

services:
  postgres:
    image: postgres:15.6
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - MIGRATION_VERSION=${MIGRATION_VERSION:-latest}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - .env:/config/env
      - ./migrations:/migrations/
      - ./init_scripts:/docker-entrypoint-initdb.d

  data_generation:
    build: ./data_generation
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PORT=5432
      - NUM_RECORDS=${ENTITIES_QUANTITY:-1000000}
    volumes:
      - ./data_generation:/src
    depends_on:
      - postgres

  performance_test:
    build: ./performance_test
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PORT=5432
      - ATTEMPTS=${ATTEMPTS:-3}
    volumes:
      - ./performance_test:/src
      - ./performance_test/query_performance_results:/src/query_performance_results
    depends_on:
      - postgres

  backup_service:
    build: ./backup_service
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - BACKUP_INTERVAL=${BACKUP_INTERVAL_HOURS:-3}
      - MAX_BACKUPS=${MAX_BACKUPS_TO_KEEP:-3}
      - POSTGRES_PORT=5432
      - BACKUP_DIR=/src/backups
    volumes:
      - ./backup_service:/src
      - ./backup_service/backups:/src/backups
    depends_on:
      - postgres